Make PojoTypes thread-safe
jdbi/jdbi pull request #2237
Opened 2022-12-20 01:35 UTC by npetryk

Fixes #2236

2022-12-20 01:39 UTC, hgschmie commented on core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoTypes.java
> +        synchronized (other.factories) {
e.g. PostgresTypes uses a ConcurrentHashMap, which is (to me) the preferred approach over adding synchronized blocks.

2022-12-20 19:22 UTC, hgschmie approved these changes

2022-12-20 19:34 UTC, hgschmie commented on core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoTypes.java
> +import java.util.concurrent.ConcurrentHashMap;
order is wrong, thus fails the build. please run the build locally (`make install` in the root folder).

2022-12-20 19:34 UTC, hgschmie requested changes
fails static code checkers

2022-12-20 19:39 UTC, stevenschlansker approved these changes
I don't think we can reliable add tests for race conditions. This looks fine to me.

2022-12-22 08:01 UTC, hgschmie commented
yes, it is. I would have approved the changes but the build is failing.

2022-12-22 19:03 UTC, npetryk commented
Thanks for y'all's patience. Got `make install` working locally

(Incidentally, I had to run `mvn license:format` to get around a `Some files do not have the expected license header` error 🤷 )

2022-12-26 15:01 UTC, npetryk commented
We good to go @hgschmie ?

2022-12-28 14:23 UTC, merged