Add Maven profile for revapi API compatibility checks
jdbi/jdbi pull request #2276
Opened 2023-02-08 15:44 UTC by sman-81

Revapi and revapi-maven-plugin can be found here: https://revapi.org/

- Main revapi configuration and versions defined in `jdbi3-build-parent`
- Maven profile 'revapi' defined in `jdbi3-build-parent`, goal `revapi:check`
- Modules not to be checked may set property `jdbi.check.skip-revapi=true` (e.g. modules for internal or testing use)
- Modules for which violations should not fail the build should set property `jdbi.check.fail-revapi=false`
- revapi configured to report violations but not fail the build

Revapi compares the project to the most recent release (e.g. 3.37.1-SNAPSHOT to 3.37.0) looking for violations of semantic versioning rules. The ruleset can be relaxed by configuration.

Violations found by revapi can be explicitly ignored.
I've done this in modules `core` and `freemarker` by example (they would have otherwise failed, would revert this of course before merging into master).
To other failing modules I've added `jdbi.check.fail-revapi=false`.
Therefore, the build is green despite a number of api 'problems' reported by revapi.

To see the problems look for 'revapi' in the build output, in particular for string 'API problems found' and onwards (examples below).

I have not had a look at the Maven site support of revapi (`revapi:report`).

Maven command line:
`mvn clean install -P revapi,fast -D no-docker`

This takes a little over 2 minutes on my lame Ubuntu laptop as opposed to 1:20 min without revapi. So it does add overhead but less than one would expect.

No compatibility problems found:

```
[INFO] --- revapi-maven-plugin:0.15.0:check (default) @ jdbi3-core ---
Downloading from nexus: http://nexus-swe.baag:8081/nexus/content/groups/public/org/jdbi/jdbi3-core/maven-metadata.xml
Downloaded from nexus: http://nexus-swe.baag:8081/nexus/content/groups/public/org/jdbi/jdbi3-core/maven-metadata.xml (3.0 kB at 5.7 kB/s)
[INFO] Comparing [org.jdbi:jdbi3-core:jar:3.37.0] against [org.jdbi:jdbi3-core:jar:3.37.1-SNAPSHOT] (including their transitive dependencies).
[INFO] API checks completed without failures.
```

Compatibility problems found:

```
[INFO] --- revapi-maven-plugin:0.15.0:check (default) @ jdbi3-jpa ---
Downloading from nexus: http://nexus-swe.baag:8081/nexus/content/groups/public/org/jdbi/jdbi3-jpa/maven-metadata.xml
Downloaded from nexus: http://nexus-swe.baag:8081/nexus/content/groups/public/org/jdbi/jdbi3-jpa/maven-metadata.xml (3.6 kB at 10 kB/s)
[INFO] Comparing [org.jdbi:jdbi3-jpa:jar:3.37.0] against [org.jdbi:jdbi3-jpa:jar:3.37.1-SNAPSHOT] (including their transitive dependencies).
[INFO] API problems found.
[INFO] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore these changes or provide justifications for them, add the xml snippets to your Revapi configuration for the "revapi.differences" extension.

```

2023-02-09 07:03 UTC, hgschmie requested changes
I think my biggest gripe with this is that this is big and contains a lot of things we should not care about.

- we should not turn testing on or off for separate modules. We should test all modules
- there are actual ignored differences in the core pom enumerated, this adds 70 lines for a single plugin and I assume that is not the end. THis makes me very uncomfortable. Why is that needed?
- there are freemarker classes in the freemarker pom. Can't we just limit to org.jdbi and ignore changes in everything else?

This is a pretty big PR for a basic function of "pull the previous version, run a diff". I would have expected something along the lines of "here is a bit of config for a plugin, check only org.jdbi, ignore everything that has *.internal.* or *.inlined.* in the package name, create a report". If that report shows problems, that is ok. We know we made mistakes in the past, this is intended to help us to get better.

2023-02-09 07:03 UTC, hgschmie commented on json/pom.xml
> +        <jdbi.check.fail-revapi>false</jdbi.check.fail-revapi>
wrong order?

2023-02-09 07:55 UTC, sman-81 commented
Thanks for your feedback @hgschmie 

>     * we should not turn testing on or off for separate modules. We should test all modules

What is the benefit from having revapi checks on internal and testing modules?
Noone would be interested in the findings. So they can be skipped.

>     * there are actual ignored differences in the core pom enumerated, this adds 70 lines for a single plugin and I assume that is not the end. THis makes me very uncomfortable. Why is that needed?

This is for demonstration only and will never get into master. Such ignored differences become obsolete after the release such changed API. Please see the initial comments of my PR above.

>     * there are freemarker classes in the freemarker pom. Can't we just limit to org.jdbi and ignore changes in everything else?

That's worth investigating and should be supported by the plugin.

> This is a pretty big PR for a basic function of "pull the previous version, run a diff".

The plugin is not part of the build cycle but is defined as Maven profile. I don't think its that intrusive :)
Since Maven site not something the project seems to use, I chose `revapi:check` over a site report (`revapi:report`).

3.37.0 -> 3.37.1 has a lot of API changes. So I suppose the timing of showcasing revapi just now was unfortunate.

I am still fuzzy about what we want from revapi. Following semver fully cannot be it. The major version is effectively locked at 3. If we still want to permit code changes that would require a new major according to semver, we have to relax the usage of semver and possibly also the configuration of revapi.

2023-02-09 08:03 UTC, sman-81 commented on internal/build/pom.xml
> +        <jdbi.check.fail-revapi>true</jdbi.check.fail-revapi>
That's how I had it at first. However the properties are controlled by properties in jdbi modules and the Maven profile 'revapi'. So a basepom default value will never be used.
I should remove the initialization of these properties altogether.

2023-02-09 11:13 UTC, sman-81 commented on internal/pom.xml
> +        <jdbi.check.skip-revapi>true</jdbi.check.skip-revapi>
oddly I had revapi fail on me without that property

2023-02-09 11:32 UTC, sman-81 commented on internal/pom.xml
> +        <jdbi.check.skip-revapi>true</jdbi.check.skip-revapi>
got it working

2023-05-16 07:29 UTC, sman-81 commented
Just rebased this PR to master again.

This PR adds revapi capabilities in a non-intrusive way (using a Maven profile to be activated in order to run checks).

We've talked about this on Slack and feedback was positive. However we have not really reached a decision.
@hgschmie @stevenschlansker Gentlemen, do we want revapi in the project or not? I am fine either way :)

2023-06-09 17:20 UTC, stevenschlansker commented
I am in general supportive of having stronger checks, but I don't really have experience with revapi specifically to make a decision one way or the other. The build has gotten a lot more complex recently, so my ask would be that if we bring this in for the long term, we automate enough that it does not add more manual steps to the build release process.  I defer to Henning for the rest.

2023-06-11 23:02 UTC, hgschmie commented
See also #920

2024-02-04 02:59 UTC, hgschmie commented
We shipped japicmp as part of the 3.44.0 release, which makes this PR redundant.

2024-02-04 02:59 UTC, closed without merging