Remove findbugs annotations
jdbi/jdbi pull request #2456
Opened 2023-08-07 18:44 UTC by stevenschlansker

As discussed in #2408, we should prefer the `jakarta` annotations, but that's not what actually got committed here. So clean that up

2023-08-08 04:26 UTC, hgschmie requested changes
The code in the PR replaces annotations from the spotbugs-annotations jar, not the findbugs jsr305 jar. That was eliminated in #2408. 

While it good to do so, the PR also needs to remove the jar references.

I am ok with the PR but it needs to get updated to remove the spotbugs-annotation references.

It may also make sense to add a section to the build pom akin to the basepom:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <configuration>
        <ignoredDependencies combine.children="append">
            <ignoredDependency>jakarta.annotation:jakarta.annotation-api</ignoredDependency>
    </configuration>
</plugin>
```

2023-08-08 04:26 UTC, hgschmie commented on core/src/main/java/org/jdbi/v3/core/Sql.java
> -import edu.umd.cs.findbugs.annotations.NonNull;
spotbugs-annotations

2023-08-08 04:27 UTC, hgschmie approved these changes

2023-08-08 04:28 UTC, hgschmie commented
actually never mind, it seems I have unlearned on how to read diffs. :-) All good. The exclusion block would still be good.

2023-08-08 04:30 UTC, hgschmie commented on core/src/main/java/org/jdbi/v3/core/interceptor/JdbiInterceptionChainHolder.java
> -    @SuppressWarnings("UnnecessaryLambda") // constant for readablity
I would have preferred that change in a separate PR. It kind of gets lost between the annotation changes.

2023-08-09 01:39 UTC, stevenschlansker commented
Why should we add a dependency ignore to the checker plugin? It passes the plugin checks fine right now.
I'll merge this and we can always tweak the build in a followup.

2023-08-09 02:35 UTC, merged